license-control.frontend-origin=${FRONTEND_ORIGIN:https://etic-system.online,https://www.etic-system.online,https://license-control.etic-system.online,https://suite.etic-system.online}
server.port=8080
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
