server.port=8081

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3307/license_system?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=America/Mexico_City&zeroDateTimeBehavior=CONVERT_TO_NULL&characterEncoding=UTF-8&connectionCollation=utf8mb4_0900_ai_ci}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:etic_local}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:etic_local_password}

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

management.endpoints.web.exposure.include=health,info
