package com.etic.licensecontrol.access;

import com.etic.licensecontrol.common.CrudService;
import java.util.*;
import org.springframework.transaction.annotation.Transactional;
import org.springframework.web.bind.annotation.*;

@RestController @RequestMapping("/api/admin")
public class AssignmentsController {
    private final CrudService c;private final AttributeValueService values; AssignmentsController(CrudService c,AttributeValueService values){this.c=c;this.values=values;}
    @GetMapping("/users/{userId}/systems") List<Map<String,Object>> systems(@PathVariable String userId){return c.db().queryForList("SELECT usa.*,s.Code System_Code,s.Name System_Name FROM user_system_access usa JOIN systems s ON s.Id_System=usa.Id_System WHERE usa.Id_User=:u",Map.of("u",userId)).stream().map(CrudService::formatDates).toList();}
    @PostMapping("/users/{userId}/systems") void system(@PathVariable String userId,@RequestBody Map<String,Object>b){b.putIfAbsent("Valid_From",null);b.putIfAbsent("Valid_Until",null);new com.etic.licensecontrol.common.InputValidator(c.db()).validate("user_system_access",b);if(b.get("Valid_From")!=null&&b.get("Valid_Until")!=null&&b.get("Valid_From").toString().compareTo(b.get("Valid_Until").toString())>0)throw new IllegalArgumentException("Vigencia inválida");Map<String,Object>p=new HashMap<>(b);p.put("u",userId);p.put("id",UUID.randomUUID().toString());c.db().update("INSERT INTO user_system_access(Id_User_System_Access,Id_User,Id_System,Status,Valid_From,Valid_Until) VALUES(:id,:u,:Id_System,:Status,:Valid_From,:Valid_Until) ON DUPLICATE KEY UPDATE Status=VALUES(Status),Valid_From=VALUES(Valid_From),Valid_Until=VALUES(Valid_Until)",p);c.audit("user_system_access",userId,"UPDATE");}
    @GetMapping("/users/{userId}/systems/{systemId}/roles") List<Map<String,Object>> roles(@PathVariable String userId,@PathVariable String systemId){return c.db().queryForList("SELECT r.*,IF(usr.Id_User IS NULL,0,1) Assigned FROM roles r LEFT JOIN user_system_roles usr ON usr.Id_Role=r.Id_Role AND usr.Id_User=:u AND usr.Id_System=:s WHERE r.Id_System=:s",Map.of("u",userId,"s",systemId)).stream().map(CrudService::formatDates).toList();}
    @PutMapping("/users/{userId}/systems/{systemId}/roles") @Transactional void roles(@PathVariable String userId,@PathVariable String systemId,@RequestBody List<String> ids){if(c.db().queryForObject("SELECT COUNT(*) FROM user_system_access WHERE Id_User=:u AND Id_System=:s",Map.of("u",userId,"s",systemId),Integer.class)==0)throw new IllegalArgumentException("Asigne primero el sistema");c.db().update("DELETE FROM user_system_roles WHERE Id_User=:u AND Id_System=:s",Map.of("u",userId,"s",systemId));for(String r:new HashSet<>(ids)){Integer valid=c.db().queryForObject("SELECT COUNT(*) FROM roles WHERE Id_Role=:r AND Id_System=:s AND Status='ACTIVE'",Map.of("r",r,"s",systemId),Integer.class);if(valid==0)throw new IllegalArgumentException("El rol no pertenece al sistema");c.db().update("INSERT INTO user_system_roles(Id_User,Id_System,Id_Role) VALUES(:u,:s,:r)",Map.of("u",userId,"s",systemId,"r",r));}c.audit("user_system_roles",userId,"UPDATE");}
    @GetMapping("/roles/{roleId}/permissions") List<Map<String,Object>> permissions(@PathVariable String roleId){return c.db().queryForList("SELECT p.*,IF(rp.Id_Role IS NULL,0,1) Assigned FROM permissions p JOIN roles r ON r.Id_System=p.Id_System LEFT JOIN role_permissions rp ON rp.Id_Permission=p.Id_Permission AND rp.Id_Role=r.Id_Role WHERE r.Id_Role=:r",Map.of("r",roleId));}
    @PutMapping("/roles/{roleId}/permissions") @Transactional void permissions(@PathVariable String roleId,@RequestBody List<String> ids){if(c.db().queryForObject("SELECT COUNT(*) FROM roles WHERE Id_Role=:r",Map.of("r",roleId),Integer.class)==0)throw new IllegalArgumentException("Rol inválido");c.db().update("DELETE FROM role_permissions WHERE Id_Role=:r",Map.of("r",roleId));for(String p:new HashSet<>(ids)){if(c.db().update("INSERT INTO role_permissions(Id_Role,Id_Permission) SELECT r.Id_Role,p.Id_Permission FROM roles r JOIN permissions p ON p.Id_System=r.Id_System WHERE r.Id_Role=:r AND p.Id_Permission=:p AND p.Status='ACTIVE'",Map.of("r",roleId,"p",p))!=1)throw new IllegalArgumentException("El permiso no pertenece al sistema del rol");}c.audit("role_permissions",roleId,"UPDATE");}
    @GetMapping("/attributes/{attributeId}/options") List<Map<String,Object>> options(@PathVariable String attributeId){return c.db().queryForList("SELECT * FROM system_attribute_options WHERE Id_Attribute=:a ORDER BY Sort_Order",Map.of("a",attributeId));}
    @PostMapping("/attributes/{attributeId}/options") void option(@PathVariable String attributeId,@RequestBody Map<String,Object>b){new com.etic.licensecontrol.common.InputValidator(c.db()).validate("system_attribute_options",b);Map<String,Object>p=new HashMap<>(b);p.put("id",UUID.randomUUID().toString());p.put("a",attributeId);c.db().update("INSERT INTO system_attribute_options(Id_Option,Id_Attribute,Value_Code,Display_Name,Sort_Order,Status) VALUES(:id,:a,:Value_Code,:Display_Name,:Sort_Order,:Status)",p);}
    @GetMapping("/users/{userId}/systems/{systemId}/attributes") List<Map<String,Object>> values(@PathVariable String userId,@PathVariable String systemId){return c.db().queryForList("SELECT a.*,v.Id_User_Attribute_Value,v.Value_Text,v.Value_Integer,v.Value_Decimal,v.Value_Boolean,v.Value_Date,v.Value_Datetime,v.Value_Json FROM system_attributes a LEFT JOIN user_system_attribute_values v ON v.Id_Attribute=a.Id_Attribute AND v.Id_User=:u AND v.Id_System=:s WHERE a.Id_System=:s AND a.Status='ACTIVE' ORDER BY a.Sort_Order",Map.of("u",userId,"s",systemId));}
    @PutMapping("/users/{userId}/systems/{systemId}/attributes/{attributeId}") void value(@PathVariable String userId,@PathVariable String systemId,@PathVariable String attributeId,@RequestBody Map<String,Object>b){values.save(userId,systemId,attributeId,b);}
    @PutMapping("/users/{userId}/systems/{systemId}") void access(@PathVariable String userId,@PathVariable String systemId,@RequestBody Map<String,Object> body){body.put("Id_System",systemId);system(userId,body);c.audit("user_system_access",userId,"UPDATE");}
    @PutMapping("/attributes/{attributeId}/options/{id}") Map<String,Object> optionUpdate(@PathVariable String attributeId,@PathVariable String id,@RequestBody Map<String,Object> body){var d=new CrudService.Definition("system_attribute_options","Id_Option",List.of("Value_Code","Display_Name","Sort_Order","Status"),List.of("Value_Code","Display_Name","Status"));if(!attributeId.equals(c.get(d,id).get("Id_Attribute")))throw new IllegalArgumentException("Opción inválida");return c.update(d,id,body);}
}
